name: Terraform Plan

on:
  push:
    branches:
      - main
    paths:
      - "infra-setup/**"
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      TF_VAR_rg_name: ${{ secrets.TF_VAR_RG_NAME }}
      TF_VAR_storage_name: ${{ secrets.TF_VAR_STORAGE_NAME }}
      TF_VAR_container_name: ${{ secrets.TF_VAR_CONTAINER_NAME }}
      TF_VAR_tfstate_key: ${{ secrets.TF_VAR_TFSTATE_INFRA_KEY }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_AZUREAD: TRUE

    defaults:
      run:
        shell: bash
        working-directory: ./infra-setup

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${TF_VAR_rg_name}" \
            -backend-config="storage_account_name=${TF_VAR_storage_name}" \
            -backend-config="container_name=${TF_VAR_container_name}" \
            -backend-config="key=${TF_VAR_tfstate_key}"
        working-directory: infra-setup

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra-setup

      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan
        working-directory: infra-setup

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: tfplan
          path: infra-setup/tfplan
